alter table public.titles add column if not exists tmdb_id int;
alter table public.titles add column if not exists imdb_id text unique;
alter table public.titles add column if not exists imdb_rank int;
alter table public.titles add column if not exists imdb_rating numeric(3,1);
alter table public.titles add column if not exists imdb_votes int;
create index if not exists titles_imdb_rank_idx on public.titles (type, imdb_rank) where imdb_rank is not null;

insert into public.titles (
  slug, title, type, tmdb_id, imdb_id, imdb_rank, imdb_rating, imdb_votes, year, country, network, duration,
  rating, synopsis, poster_path, backdrop_path, genre_names, is_published, is_featured, is_trending, is_recently_added
) values
('the-shawshank-redemption-1994', 'The Shawshank Redemption', 'movie', 278, 'tt0111161', 1, 9.3, 3196742, 1994, 'Unknown', 'Movie', '2j 22m', 'IMDb 9.3', 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.', '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg', '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg', array['Drama'], true, true, true),
('the-godfather-1972', 'The Godfather', 'movie', 238, 'tt0068646', 2, 9.2, 2229956, 1972, 'Unknown', 'Movie', '2j 55m', 'IMDb 9.2', 'Patriark tua dari dinasti kejahatan terorganisir di New York City pascaperang mengalihkan kendali kerajaan klandestinnya kepada putra bungsunya yang enggan.', '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', '/ejdD20cdHNFAYAN2DlqPToXKyzx.jpg', array['Crime', 'Drama'], true, true, true),
('the-dark-knight-2008', 'The Dark Knight', 'movie', 155, 'tt0468569', 3, 9.1, 3176249, 2008, 'Unknown', 'Movie', '2j 32m', 'IMDb 9.1', 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.', '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', '/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg', array['Crime', 'Thriller'], true, true, true),
('the-chaos-class-1975', 'The Chaos Class', 'movie', 83651, 'tt0252487', 4, 9.1, 46317, 1975, 'Unknown', 'Movie', '1j 25m', 'IMDb 9.1', 'A group of affluent private school slackers enjoy a prankster lifestyle until a tough new disciplinarian headmaster arrives.', '/t2xLuEeZhy4uyiWIFT9D4mmyEA8.jpg', '/9u9XcPaeOvPcelm8RmMarEgvIAk.jpg', array['Comedy'], true, true, true),
('the-lord-of-the-rings-the-return-of-the-king-2003', 'The Lord of the Rings: The Return of the King', 'movie', 122, 'tt0167260', 5, 9.0, 2168090, 2003, 'Unknown', 'Movie', '3j 21m', 'IMDb 9.0', 'Aragorn dinyatakan sebagai pewaris raja-raja kuno saat ia, Gandalf dan anggota-anggota lain dari persekutuan yang rusak berjuang untuk menyelamatkan Gondor dari pasukan Sauron. Sementara itu, Frodo dan Sam membawa cincin itu lebih dekat ke jantung Mordor, kerajaan penguasa gelap.', '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg', '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg', array['Adventure', 'Drama', 'Fantasy'], true, true, true),
('schindler-s-list-1993', 'Schindler''s List', 'movie', 424, 'tt0108052', 6, 9.0, 1586996, 1993, 'Unknown', 'Movie', '3j 15m', 'IMDb 9.0', 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.', '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg', '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg', array['Biography', 'Drama', 'History'], false, true, true),
('the-godfather-part-ii-1974', 'The Godfather Part II', 'movie', 240, 'tt0071562', 7, 9.0, 1496738, 1974, 'Unknown', 'Movie', '3j 22m', 'IMDb 9.0', 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.', '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg', '/kGzFbGhp99zva6oZODW5atUtnqi.jpg', array['Crime', 'Drama'], false, true, true),
('12-angry-men-1957', '12 Angry Men', 'movie', 389, 'tt0050083', 8, 9.0, 986312, 1957, 'Unknown', 'Movie', '1j 36m', 'IMDb 9.0', 'Setelah argumen penutup dalam persidangan pembunuhan, 12 anggota juri harus berunding, dengan vonis bersalah yang berarti kematian bagi terdakwa, seorang remaja dari kota. Ketika belasan orang itu mencoba untuk mencapai keputusan bulat saat diasingkan di sebuah ruangan, seorang juri meragukan beberapa elemen dari kasus tersebut. Masalah pribadi segera muncul ke permukaan, dan konflik mengancam untuk menggagalkan proses rumit yang akan menentukan nasib seorang anak laki-laki.', '/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg', '/qqHQsStV6exghCM7zbObuYBiYxw.jpg', array['Crime', 'Drama'], false, true, true),
('attack-on-titan-the-last-attack-2024', 'Attack on Titan: THE LAST ATTACK', 'movie', 1333100, 'tt33175825', 9, 9.0, 30549, 2024, 'Unknown', 'Movie', '2j 25m', 'IMDb 9.0', 'A colossal-sized omnibus film bringing together the last two episodes of Attack on Titan in the franchise''s first-ever theatrical experience. After venturing beyond the walls and separated from his comrades, Eren finds himself inspired by this new truth and plots the "Rumbling," a terrifying plan to eradicate every living thing in the world. With the fate of the world hanging in the balance, a motley crew of Eren''s former comrades and enemies scramble to halt his deadly mission. The only question is, can they stop him?', '/wgwldDDlTDDMrluOMkpSA8lyKjv.jpg', '/nB6IR9XfdRpVRKCz85uT97EjgwB.jpg', array['Action', 'Adventure', 'Animation'], false, true, true),
('the-lord-of-the-rings-the-fellowship-of-the-ring-2001', 'The Lord of the Rings: The Fellowship of the Ring', 'movie', 120, 'tt0120737', 10, 8.9, 2210277, 2001, 'Unknown', 'Movie', '2j 58m', 'IMDb 8.9', 'Hobbit muda Frodo Baggins, setelah mewarisi cincin misterius dari pamannya, Bilbo, harus meninggalkan rumahnya agar tidak jatuh ke tangan penciptanya yang jahat. Sepanjang jalan, persekutuan dibentuk untuk melindungi ringbearer dan memastikan bahwa cincin itu tiba di tujuan akhirnya: Mt. Doom, satu-satunya tempat di mana ia bisa dihancurkan.', '/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg', '/oiwc338EoBgS4sEI2ixAny4KQKg.jpg', array['Adventure', 'Drama', 'Fantasy'], false, true, true),
('david-attenborough-a-life-on-our-planet-2020', 'David Attenborough: A Life on Our Planet', 'movie', 664280, 'tt11989890', 11, 8.9, 36186, 2020, 'Unknown', 'Movie', '1j 23m', 'IMDb 8.9', 'The story of life on our planet by the man who has seen more of the natural world than any other. In more than 90 years, Attenborough has visited every continent on the globe, exploring the wild places of our planet and documenting the living world in all its variety and wonder. Addressing the biggest challenges facing life on our planet, the film offers a powerful message of hope for future generations.', '/zSKwyUDKDHiFU5syTTvQRDcGBPS.jpg', '/hHL4pwGzYS4njLpXhIjfc9skAQJ.jpg', array['Biography', 'Documentary'], false, true, true),
('mirror-game-2016', 'Mirror Game', 'movie', 418325, 'tt5354160', 12, 8.9, 31047, 2016, 'Unknown', 'Movie', '2j 27m', 'IMDb 8.9', 'Ayna is an actor and the prison is his stage. He slips into the characters of the powerful convicted in exchange of money and take their place in prison. This strange profession is borne out of a society that doesn''t give him a chance to follow his passion of acting, but forces him to act in the real life. Falling in love with the girl next door changes his life equation and he decides to end this career with one last performance. But this one takes him too deep in the rabbit hole. The story unfolds on how an underdog survives in a society that is merciless and struggles his way out from the clutch of crime game which he is a part too.', '/1Cz5Q7PH2JklNV7OzMkTenPGrEf.jpg', '/weDuRCMSCXgVQNQmSsfCQtdAmoK.jpg', array['Crime', 'Mystery', 'Thriller'], false, true, true),
('tosun-pasha-1976', 'Tosun Pasha', 'movie', 38794, 'tt0253828', 13, 8.9, 26433, 1976, 'Unknown', 'Movie', '1j 30m', 'IMDb 8.9', 'Late 19th century in Alexandria. Two traditionally rival Turkish families, "Seferoglu"s and "Tellioglu"s are competing for the "Green Valley". The winner will be determined by Daver Bey, who has a beautiful young daughter, Leyla. Both families try to arrange a marriage between a man from their family and Leyla, so that Daver Bey will be inclined to give the green valley to his "relatives". Tellioglus, who are behind in the race, desperately find a final solution: They will fake their idiotic butler, Saban, as the highest ranked Ottoman soldier in Egypt: Tosun Pasha.', '/zqgB6E4yynfxkzzOurzC0VRObxf.jpg', '/kiu0xIcu9Rju9HTWSJOo8Svg9aW.jpg', array['Comedy', 'History'], false, true, true),
('inception-2010', 'Inception', 'movie', 27205, 'tt1375666', 14, 8.8, 2824348, 2010, 'Unknown', 'Movie', '2j 28m', 'IMDb 8.8', 'Cobb, seorang pencuri terampil yang melakukan spionase perusahaan dengan menyusup ke alam bawah sadar targetnya ditawarkan kesempatan untuk mendapatkan kembali kehidupan lamanya sebagai pembayaran untuk tugas yang dianggap mustahil: "permulaan", penanaman ide orang lain ke dalam alam bawah sadar target.', '/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg', '/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg', array['Adventure', 'Sci-Fi', 'Thriller'], false, true, true),
('fight-club-1999', 'Fight Club', 'movie', 550, 'tt0137523', 15, 8.8, 2615814, 1999, 'Unknown', 'Movie', '2j 19m', 'IMDb 8.8', 'Seorang pekerja kantoran yang menderita insomnia dan pembuat sabun yang sangat peduli membentuk klub pertarungan bawah tanah yang berkembang menjadi lebih banyak lagi.', '/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg', '/xRyINp9KfMLVjRiO5nCsoRDdvvF.jpg', array['Crime', 'Drama', 'Thriller'], false, true, true),
('forrest-gump-1994', 'Forrest Gump', 'movie', 13, 'tt0109830', 16, 8.8, 2502882, 1994, 'Unknown', 'Movie', '2j 22m', 'IMDb 8.8', 'Forrest Gump, seorang pria ber IQ rendah - namun baik hati, bergabung dengan tentara untuk mengabdi. Namun, benaknya seolah tidak bisa berhenti memikirkan sang kekasih masa kecilnya, Jenny Curran.', '/Cw4hIUIAmSYfK9QfaUW5igp9La.jpg', '/66Kn4XWhkuPkJxOJyPEx4U2CUfN.jpg', array['Drama', 'Romance'], false, true, true),
('pulp-fiction-1994', 'Pulp Fiction', 'movie', 680, 'tt0110912', 17, 8.8, 2439449, 1994, 'Unknown', 'Movie', '2j 34m', 'IMDb 8.8', 'A burger-loving hit man, his philosophical partner, a drug-addled gangster''s moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.', '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg', '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg', array['Crime', 'Drama'], false, true, true),
('the-lord-of-the-rings-the-two-towers-2002', 'The Lord of the Rings: The Two Towers', 'movie', 121, 'tt0167261', 18, 8.8, 1961603, 2002, 'Unknown', 'Movie', '2j 59m', 'IMDb 8.8', 'Frodo dan Sam sedang berjalan ke Mordor untuk menghancurkan Satu Cincin Kekuasaan sementara Gimli, Legolas dan Aragorn mencari Merry dan Pippin yang ditangkap Orc. Selama ini, penyihir jahat Saruman menunggu anggota Fellowship di Menara Orthanc di Isengard.', '/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg', '/6G73mNyooWAEQTpckPSnFxFoNmc.jpg', array['Adventure', 'Drama', 'Fantasy'], false, true, true),
('the-good-the-bad-and-the-ugly-1966', 'The Good, the Bad and the Ugly', 'movie', 429, 'tt0060196', 19, 8.8, 891500, 1966, 'Unknown', 'Movie', '2j 58m', 'IMDb 8.8', 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.', '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg', '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg', array['Adventure', 'Drama', 'Western'], false, true, true),
('interstellar-2014', 'Interstellar', 'movie', 157336, 'tt0816692', 20, 8.7, 2541567, 2014, 'Unknown', 'Movie', '2j 49m', 'IMDb 8.7', 'Antarbintang mencatat petualangan sekelompok penjelajah yang memanfaatkan lubang cacing yang baru ditemukan untuk melampaui batasan perjalanan ruang angkasa manusia dan menaklukkan jarak yang luas yang terlibat dalam pelayaran antarbintang.', '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg', '/2ssWTSVklAEc98frZUQhgtGHx7s.jpg', array['Adventure', 'Drama', 'Sci-Fi'], false, true, true),
('the-matrix-1999', 'The Matrix', 'movie', 603, 'tt0133093', 21, 8.7, 2252453, 1999, 'Unknown', 'Movie', '2j 16m', 'IMDb 8.7', 'Berlatar abad ke-22, The Matrix menceritakan tentang seorang peretas komputer yang bergabung dengan sekelompok pemberontak bawah tanah melawan komputer-komputer besar dan kuat yang kini menguasai bumi.', '/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg', '/oMsxZEvz9a708d49b6UdZK1KAo5.jpg', array['Action', 'Sci-Fi'], false, false, true),
('star-wars-episode-v-the-empire-strikes-back-1980', 'Star Wars: Episode V - The Empire Strikes Back', 'movie', 1891, 'tt0080684', 22, 8.7, 1507380, 1980, 'Unknown', 'Movie', '2j 04m', 'IMDb 8.7', 'Kisah epik ini berlanjut saat Luke Skywalker, dengan harapan mengalahkan Kekaisaran Galaksi yang jahat, mempelajari cara-cara Jedi dari guru tua Yoda. Namun Darth Vader lebih bertekad dari sebelumnya untuk menangkap Luke. Sementara itu, pemimpin pemberontak Putri Leia, Han Solo yang sombong, Chewbacca, dan droid C-3PO dan R2-D2 dilemparkan ke berbagai tahap penangkapan, pengkhianatan, dan keputusasaan.', '/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg', '/aJCtkxLLzkk1pECehVjKHA2lBgw.jpg', array['Adventure', 'Fantasy', 'Sci-Fi'], false, false, true),
('goodfellas-1990', 'GoodFellas', 'movie', 769, 'tt0099685', 23, 8.7, 1394837, 1990, 'Unknown', 'Movie', '2j 25m', 'IMDb 8.7', 'Mantan mafia, Henry Hill, menceritakan kisah suka dukanya yang penuh warna tapi brutal dalam keluarga kriminal New York. Impian untuk hidup mewah pun jadi mimpi buruk.', '/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg', '/gILte6Zd7m1YneIr6MVhh30S9pr.jpg', array['Biography', 'Crime', 'Drama'], false, false, true),
('12th-fail-2023', '12th Fail', 'movie', 1163258, 'tt23849204', 24, 8.7, 172902, 2023, 'Unknown', 'Movie', '2j 27m', 'IMDb 8.7', 'Based on the true story of IPS officer Manoj Kumar Sharma, 12th Fail sheds limelight on fearlessly embracing the idea of restarting the academic journey despite the setbacks and challenges and reclaiming one''s destiny at a place where millions of students attempt the world''s toughest competitive exam: UPSC.', '/eebUPRI4Z5e1Z7Hev4JZAwMIFkX.jpg', '/6RV2o8PBCEyw9ylOWViV1CtULIF.jpg', array['Biography', 'Drama'], false, false, true),
('777-charlie-2022', '777 Charlie', 'movie', 634120, 'tt7466810', 25, 8.7, 47792, 2022, 'Unknown', 'Movie', '2j 44m', 'IMDb 8.7', 'Dharma is stuck in a rut with his negative and lonely lifestyle and spends each day in the comfort of his loneliness. A pup named Charlie who is naughty and energetic which is a complete contrast with the Dharma’s character enters his life and gives him a new perspective towards it.', '/qArPmXH0aWsT3SEtYl8XrU2Oz48.jpg', '/3Sdi32wfIIOtDz1hYik6bGe1iWC.jpg', array['Adventure', 'Comedy', 'Drama'], false, false, true),
('kill-bill-the-whole-bloody-affair-2004', 'Kill Bill: The Whole Bloody Affair', 'movie', 414419, 'tt6019206', 26, 8.7, 44107, 2004, 'Unknown', 'Movie', '4j 13m', 'IMDb 8.7', 'A former assassin, known simply as The Bride, wakes from a coma four years after her jealous ex-lover Bill attempts to murder her on her wedding day. Fueled by an insatiable desire for revenge, she vows to get even with every person who contributed to the loss of her unborn child, her entire wedding party, and four years of her life. After devising a hit list, The Bride sets off on her quest, enduring unspeakable injury and unscrupulous enemies.', '/nSOJfWJCdVFZQwXQA7RXn7FIIiY.jpg', '/qe4Tp0hURXqiih5AV1kHimXIt3u.jpg', array['Action', 'Crime', 'Thriller'], false, false, true),
('se7en-1995', 'Se7en', 'movie', 807, 'tt0114369', 27, 8.6, 2027153, 1995, 'Unknown', 'Movie', '2j 07m', 'IMDb 8.6', 'Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the "seven deadly sins" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Somerset researches each sin in an effort to get inside the killer''s mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.', '/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg', '/i5H7zusQGsysGQ8i6P361Vnr0n2.jpg', array['Crime', 'Drama', 'Mystery'], false, false, true),
('the-silence-of-the-lambs-1991', 'The Silence of the Lambs', 'movie', 274, 'tt0102926', 28, 8.6, 1726667, 1991, 'Unknown', 'Movie', '1j 58m', 'IMDb 8.6', 'Clarice Starling is a top student at the FBI''s training academy. Jack Crawford wants Clarice to interview Dr. Hannibal Lecter, a brilliant psychiatrist who is also a violent psychopath, serving life behind bars for various acts of murder and cannibalism. Crawford believes that Lecter may have insight into a case and that Starling, as an attractive young woman, may be just the bait to draw him out.', '/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg', '/aYcnDyLMnpKce1FOYUpZrXtgUye.jpg', array['Crime', 'Drama', 'Horror'], false, false, true),
('saving-private-ryan-1998', 'Saving Private Ryan', 'movie', 857, 'tt0120815', 29, 8.6, 1644125, 1998, 'Unknown', 'Movie', '2j 49m', 'IMDb 8.6', 'Delapan Ranger Angkatan Darat AS menyusup ke wilayah yang dikuasai Jerman pada saat Perang Dunia II demi membawa pulang seorang prajurit yang tiga kakaknya telah gugur.', '/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg', '/bdD39MpSVhKjxarTxLSfX6baoMP.jpg', array['Drama', 'War'], false, false, true),
('star-wars-episode-iv-a-new-hope-1977', 'Star Wars: Episode IV - A New Hope', 'movie', 11, 'tt0076759', 30, 8.6, 1572710, 1977, 'Unknown', 'Movie', '2j 01m', 'IMDb 8.6', 'Putri Leia ditangkap dan disandera oleh pasukan Kekaisaran jahat dalam upaya mereka untuk mengambil alih Kekaisaran galaksi. Venturesome Luke Skywalker dan kapten gagah tim Han Solo bersama dengan duo robot yang dicintai R2-D2 dan C-3PO untuk menyelamatkan putri cantik dan memulihkan kedamaian dan keadilan di Kekaisaran.', '/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg', '/4qCqAdHcNKeAHcK8tJ8wNJZa9cx.jpg', array['Adventure', 'Fantasy', 'Sci-Fi'], false, false, true),
('the-green-mile-1999', 'The Green Mile', 'movie', 497, 'tt0120689', 31, 8.6, 1564499, 1999, 'Unknown', 'Movie', '3j 09m', 'IMDb 8.6', 'A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people''s ailments. When the cell block''s head guard, Paul Edgecomb, recognizes Coffey''s miraculous gift, he tries desperately to help stave off the condemned man''s execution.', '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg', '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg', array['Crime', 'Drama', 'Fantasy'], false, false, true),
('terminator-2-judgment-day-1991', 'Terminator 2: Judgment Day', 'movie', 280, 'tt0103064', 32, 8.6, 1286448, 1991, 'Unknown', 'Movie', '2j 17m', 'IMDb 8.6', 'Ten years after the events of the original, a reprogrammed T-800 is sent back in time to protect young John Connor from the shape-shifting T-1000. Together with his mother Sarah, he fights to stop Skynet from triggering a nuclear apocalypse.', '/jFTVD4XoWQTcg7wdyJKa8PEds5q.jpg', '/izkMjmhauFx9DjoBQqM5sM5WAwE.jpg', array['Action', 'Adventure', 'Sci-Fi'], false, false, true),
('one-flew-over-the-cuckoo-s-nest-1975', 'One Flew Over the Cuckoo''s Nest', 'movie', 510, 'tt0073486', 33, 8.6, 1157599, 1975, 'Unknown', 'Movie', '2j 13m', 'IMDb 8.6', 'A petty criminal fakes insanity to serve his sentence in a mental ward rather than prison. He soon finds himself as a leader to the other patients—and an enemy to the cruel, domineering nurse who runs the ward.', '/kjWsMh72V6d8KRLV4EOoSJLT1H7.jpg', '/vMylmakO2K9cZexNUze8wa9muJp.jpg', array['Drama'], false, false, true),
('spirited-away-2001', 'Spirited Away', 'movie', 129, 'tt0245429', 34, 8.6, 970141, 2001, 'Unknown', 'Movie', '2j 04m', 'IMDb 8.6', 'Seorang anak perempuan berusia 10 tahun semakin jauh dari orangtuanya, memasuki dunia yang dikuasai oleh para binatang aneh yang mirip monster. Akankah dia bisa melihat kembali dunia seperti semula?', '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg', array['Adventure', 'Animation', 'Family'], false, false, true),
('city-of-god-2002', 'City of God', 'movie', 598, 'tt0317248', 35, 8.6, 872542, 2002, 'Unknown', 'Movie', '2j 10m', 'IMDb 8.6', 'In the poverty-stricken favelas of Rio de Janeiro in the 1970s, two young men choose different paths. Rocket is a budding photographer who documents the increasing drug-related violence of his neighborhood, while José “Zé” Pequeno is an ambitious drug dealer diving into a dangerous life of crime.', '/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg', '/uvitbjFU4JqvMwIkMWHp69bmUzG.jpg', array['Crime', 'Drama'], false, false, true),
('life-is-beautiful-1997', 'Life Is Beautiful', 'movie', 637, 'tt0118799', 36, 8.6, 814371, 1997, 'Unknown', 'Movie', '1j 56m', 'IMDb 8.6', 'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.', '/6tEJnof1DKWPnl5lzkjf0FVv7oB.jpg', '/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg', array['Comedy', 'Drama', 'Romance'], false, false, true),
('it-s-a-wonderful-life-1946', 'It''s a Wonderful Life', 'movie', 1585, 'tt0038650', 37, 8.6, 554461, 1946, 'Unknown', 'Movie', '2j 10m', 'IMDb 8.6', 'George Bailey has spent his entire life giving to the people of Bedford Falls. All that prevents rich skinflint Mr. Potter from taking over the entire town is George''s modest building and loan company. But on Christmas Eve the business''s $8,000 is lost and George''s troubles begin.', '/bSqt9rhDZx1Q7UZ86dBPKdNomp2.jpg', '/3q35nBLCIdEbxYfsr7D5ocYQXKz.jpg', array['Drama', 'Family', 'Fantasy'], false, false, true),
('seven-samurai-1954', 'Seven Samurai', 'movie', 346, 'tt0047478', 38, 8.6, 402263, 1954, 'Unknown', 'Movie', '3j 27m', 'IMDb 8.6', 'A samurai answers a village''s request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.', '/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg', '/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg', array['Action', 'Drama'], false, false, true),
('jai-bhim-2021', 'Jai Bhim', 'movie', 855400, 'tt15097216', 39, 8.6, 234648, 2021, 'Unknown', 'Movie', '2j 44m', 'IMDb 8.6', 'A pregnant woman from a primitive tribal community, searches desperately for her husband, who is missing from police custody. So as to find her husband and seek justice for them, as their voice, a High Court advocate rises in support. Will their battle for justice succeed?', '/ehybiOtBUtrMkmtB39zQEtq1Jie.jpg', '/40lmQ5vzKJhj5k7i0hvZuglneyj.jpg', array['Crime', 'Drama'], false, false, true),
('soorarai-pottru-2020', 'Soorarai Pottru', 'movie', 595228, 'tt10189514', 40, 8.6, 132087, 2020, 'Unknown', 'Movie', '2j 33m', 'IMDb 8.6', 'Nedumaaran Rajangam "Maara" sets out to make the common man fly and in the process takes on the world''s most capital intensive industry and several enemies who stand in his way.', '/5uimlxPCgAei8JfQUDFEUQLoyyh.jpg', '/tZDdwUFL9OLhx2AhSMjKsg4abNb.jpg', array['Drama'], false, false, true),
('harakiri-1962', 'Harakiri', 'movie', 14537, 'tt0056058', 41, 8.6, 91810, 1962, 'Unknown', 'Movie', '2j 13m', 'IMDb 8.6', 'Down-on-his-luck veteran Tsugumo Hanshirō enters the courtyard of the prosperous House of Iyi. Unemployed, and with no family, he hopes to find a place to commit seppuku—and a worthy second to deliver the coup de grâce in his suicide ritual. The senior counselor for the Iyi clan questions the ronin’s resolve and integrity, suspecting Hanshirō of seeking charity rather than an honorable end. What follows is a pair of interlocking stories which lay bare the difference between honor and respect, and promises to examine the legendary foundations of the Samurai code.', '/zK7HsOC7QxW1ldKIeFG8YJ5F2Eb.jpg', '/e3hG3uadtcP0pYdRa5ch4ysQW76.jpg', array['Drama', 'Mystery'], false, false, true),
('rocketry-the-nambi-effect-2022', 'Rocketry: The Nambi Effect', 'movie', 607145, 'tt9263550', 42, 8.6, 62215, 2022, 'Unknown', 'Movie', '2j 37m', 'IMDb 8.6', 'The story of the great Indian rocket scientist, Shri Nambi Narayanan''s life, a true patriot, who was turned into a villain in the blink of an eye after being falsely accused of treason.', '/o7A1agEoXvwyyOmIbHnUhfnC34j.jpg', '/nkdXBPZmX7i2Dt8MKSYjmPPF7ov.jpg', array['Biography', 'Drama'], false, false, true),
('20-days-in-mariupol-2023', '20 Days in Mariupol', 'movie', 1058616, 'tt24082438', 43, 8.6, 58076, 2023, 'Unknown', 'Movie', '1j 37m', 'IMDb 8.6', 'As the Russian invasion begins, a team of Ukrainian journalists trapped in the besieged city of Mariupol struggle to continue their work documenting the war''s atrocities.', '/zIRp1IeuPh4GgqFCH3y0DQuY9xP.jpg', '/986n9SAXsuxpPJzFAWK3azPknX0.jpg', array['Documentary', 'War'], false, false, true),
('anbe-sivam-2003', 'Anbe Sivam', 'movie', 26910, 'tt0367495', 44, 8.6, 28330, 2003, 'Unknown', 'Movie', '2j 40m', 'IMDb 8.6', 'Anbarasu, young and arrogant, and Nallasivam, damaged - physically but not spiritually - by life, are thrown together by circumstances, and find that they are in some ways bound together by fate.', '/nT556HbikCCLABe8xQ4zQ2QIb0O.jpg', '/9QaebfA43SkffIy6sDFje5q0jdk.jpg', array['Adventure', 'Comedy', 'Drama'], false, false, true),
('nayakan-1987', 'Nayakan', 'movie', 29971, 'tt0093603', 45, 8.6, 27930, 1987, 'Unknown', 'Movie', '2j 25m', 'IMDb 8.6', 'Velu Naicker, who witnesses the brutal murder of his father, kills a corrupt policeman and escapes to Mumbai, only to become a gangster.', '/hnCKKPG5VkUiGQV0DTniyMTEZsT.jpg', '/u4iRTMD0oJPUP2kjmH3XIEhsDKF.jpg', array['Crime', 'Drama'], false, false, true),
('django-unchained-2012', 'Django Unchained', 'movie', 68718, 'tt1853728', 46, 8.5, 1887964, 2012, 'Unknown', 'Movie', '2j 45m', 'IMDb 8.5', 'Ditemani oleh pemburu hadiah asal Jerman, seorang budak yang dibebaskan bernama Django melintasi Amerika demi membebaskan istrinya dari pemilik perkebunan yang sadis.', '/28fQUdbUKkNBGkhYhiUt4Wbxt5O.jpg', '/2oZklIzUbvZXXzIFzv7Hi68d6xf.jpg', array['Drama', 'Western'], false, false, true),
('gladiator-2000', 'Gladiator', 'movie', 98, 'tt0172495', 47, 8.5, 1853968, 2000, 'Unknown', 'Movie', '2j 35m', 'IMDb 8.5', 'Seorang mantan Jenderal Romawi bertekad membalas dendam terhadap kaisar korup yang membunuh keluarganya dan mengirimnya ke perbudakan.', '/wN2xWp1eIwCKOD0BHTcErTBv1Uq.jpg', '/jhk6D8pim3yaByu1801kMoxXFaX.jpg', array['Action', 'Adventure', 'Drama'], false, false, true),
('the-prestige-2006', 'The Prestige', 'movie', 1124, 'tt0482571', 48, 8.5, 1593444, 2006, 'Unknown', 'Movie', '2j 10m', 'IMDb 8.5', 'A mysterious story of two magicians whose intense rivalry leads them on a life-long battle for supremacy -- full of obsession, deceit and jealousy with dangerous and deadly consequences.', '/Ag2B2KHKQPukjH7WutmgnnSNurZ.jpg', '/z3br1ub7spqGMkxgjgJSdM4DC21.jpg', array['Drama', 'Mystery', 'Sci-Fi'], false, false, true),
('the-departed-2006', 'The Departed', 'movie', 1422, 'tt0407887', 49, 8.5, 1557866, 2006, 'Unknown', 'Movie', '2j 31m', 'IMDb 8.5', 'To take down South Boston''s Irish Mafia, the police send in one of their own to infiltrate the underworld, not realizing the syndicate has done likewise. While an undercover cop curries favor with the mob kingpin, a career criminal rises through the police ranks. But both sides soon discover there''s a mole among them.', '/nT97ifVT2J1yMQmeq20Qblg61T.jpg', '/6WRrGYalXXveItfpnipYdayFkQB.jpg', array['Crime', 'Drama', 'Thriller'], false, false, true),
('back-to-the-future-1985', 'Back to the Future', 'movie', 105, 'tt0088763', 50, 8.5, 1455912, 1985, 'Unknown', 'Movie', '1j 56m', 'IMDb 8.5', 'Eighties teenager Marty McFly is accidentally sent back in time to 1955, inadvertently disrupting his parents'' first meeting and attracting his mother''s romantic interest. Marty must repair the damage to history by rekindling his parents'' romance and - with the help of his eccentric inventor friend Doc Brown - return to 1985.', '/vN5B5WgYscRGcQpVhHl6p9DDTP0.jpg', '/5bzPWQ2dFUl2aZKkp7ILJVVkRed.jpg', array['Adventure', 'Comedy', 'Sci-Fi'], false, false, true),
('breaking-bad-2008', 'Breaking Bad', 'series', 1396, 'tt0903747', 1, 9.5, 2627687, 2008, 'Unknown', 'TV', '1 Musim', 'IMDb 9.5', 'Ketika Walter White, seorang guru kimia New Mexico, didiagnosis dengan kanker stadium III dan diberi prognosis hanya dua tahun lagi untuk hidup. Dia dipenuhi dengan rasa tidak takut dan keinginan yang tak henti-hentinya untuk mengamankan masa depan keuangan keluarganya dengan biaya berapa pun ketika dia memasuki dunia narkoba dan kejahatan yang berbahaya.', '/3xnWaLQjelJDDF7LT1WBo6f4BRe.jpg', '/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg', array['Crime', 'Drama', 'Thriller'], true, true, true),
('avatar-the-last-airbender-2005', 'Avatar: The Last Airbender', 'series', 246, 'tt0417299', 2, 9.3, 444431, 2005, 'Unknown', 'TV', '1 Musim', 'IMDb 9.3', 'In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.', '/7nYD5vKvr0JVxkl6QNCkLSQZfHJ.jpg', '/7oBGhqJIghRBvOwo5Qe0yM0cnMc.jpg', array['Action', 'Adventure', 'Animation'], true, true, true),
('the-wire-2002', 'The Wire', 'series', 1438, 'tt0306414', 3, 9.3, 432303, 2002, 'Unknown', 'TV', '1 Musim', 'IMDb 9.3', 'Told from the points of view of both the Baltimore homicide and narcotics detectives and their targets, the series captures a universe in which the national war on drugs has become a permanent, self-sustaining bureaucracy, and distinctions between good and evil are routinely obliterated.', '/4lbclFySvugI51fwsyxBTOm4DqK.jpg', '/layPSOJGckJv3PXZDIVluMq69mn.jpg', array['Crime', 'Drama', 'Thriller'], true, true, true),
('bluey-2018', 'Bluey', 'series', 82728, 'tt7678620', 4, 9.3, 47933, 2018, 'Unknown', 'TV', '1 Musim', 'IMDb 9.3', 'Bluey is an inexhaustible six year-old Blue Heeler dog, who loves to play and turns everyday family life into extraordinary adventures, developing her imagination as well as her mental, physical and emotional resilience.', '/b9mY0X5T20ZM073hoa5n0dgmbfN.jpg', '/g88VMPtog8sl8riaIRtz4U80dMK.jpg', array['Animation', 'Comedy', 'Family'], true, true, true),
('game-of-thrones-2011', 'Game of Thrones', 'series', 1399, 'tt0944947', 5, 9.2, 2622822, 2011, 'Unknown', 'TV', '1 Musim', 'IMDb 9.2', 'Tujuh keluarga bangsawan berjuang untuk menguasai tanah mitos Westeros. Gesekan antara rumah-rumah mengarah ke perang skala penuh. Semua sementara kejahatan yang sangat kuno terbangun di utara terjauh. Di tengah-tengah perang, perintah militer yang diabaikan, Night''s Watch, adalah yang berdiri di antara alam manusia dan kengerian es di luarnya.', '/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg', '/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg', array['Drama', 'Fantasy'], false, true, true),
('the-sopranos-1999', 'The Sopranos', 'series', 1398, 'tt0141842', 6, 9.2, 582145, 1999, 'Unknown', 'TV', '1 Musim', 'IMDb 9.2', 'The story of New Jersey-based Italian-American mobster Tony Soprano and the difficulties he faces as he tries to balance the conflicting requirements of his home life and the criminal organization he heads. Those difficulties are often highlighted through his ongoing professional relationship with psychiatrist Jennifer Melfi. The show features Tony''s family members and Mafia associates in prominent roles and story arcs, most notably his wife Carmela and his cousin and protégé Christopher Moltisanti.', '/rTc7ZXdroqjkKivFPvCPX0Ru7uw.jpg', '/lNpkvX2s8LGB0mjGODMT4o6Up7j.jpg', array['Crime', 'Drama'], false, true, true),
('sapne-vs-everyone-2023', 'Sapne vs Everyone', 'series', 240983, 'tt30263074', 7, 9.2, 85032, 2023, 'Unknown', 'TV', '1 Musim', 'IMDb 9.2', 'Two obsessive dreamers collide with the resistance of expectations, morality and each other.', '/ajBMZ9JNpfrecj4xpZz49tCONBm.jpg', '/xP8OH1O4DBd6Std0LVprox9cYQD.jpg', array['Drama'], false, true, true),
('our-planet-2019', 'Our Planet', 'series', 83880, 'tt9253866', 8, 9.2, 63096, 2019, 'Unknown', 'TV', '1 Musim', 'IMDb 9.2', 'Saksikan kecantikan alami planet kita dan renungkan bagaimana perubahan iklim memengaruhi seluruh makhluk hidup dalam dokumenter ambisius dengan lingkup spektakuler ini.', '/wRSnArnQBmeUYb5GWDU595bGsBr.jpg', '/p8EUX6MPSNLxVwqO3fCYTi896Ro.jpg', array['Documentary', 'Family'], false, true, true),
('the-world-at-war-1973', 'The World at War', 'series', 751, 'tt0071075', 9, 9.2, 37886, 1973, 'Unknown', 'TV', '1 Musim', 'IMDb 9.2', 'A documentary series that gives a historical account of the events of World War II, from its roots in the 1920s to the aftermath and the lives it profoundly influenced.', '/bWdwEYQQEsz9HuXy5m95z95BYQM.jpg', '/wJ1ppVIjxTBx2O6DHRBswH1Go6B.jpg', array['Documentary', 'History', 'War'], false, true, true),
('shingeki-no-kyojin-2013', 'Shingeki no Kyojin', 'series', 1429, 'tt2560140', 10, 9.1, 721731, 2013, 'Unknown', 'TV', '1 Musim', 'IMDb 9.1', 'Beberapa ratus tahun yang lalu, Manusia hampir dimusnahkan oleh para Titan. Titans biasanya bertingkat beberapa, tampaknya tidak memiliki kecerdasan, melahap manusia dan, yang terburuk, tampaknya melakukannya untuk kesenangan daripada sebagai sumber makanan. Sebagian kecil umat manusia bertahan dengan membangun tembok di kota yang dilindungi oleh tembok yang sangat tinggi, bahkan lebih tinggi dari Titan terbesar. Berkedip maju ke masa kini dan kota ini belum pernah melihat Titan selama lebih dari 100 tahun. Remaja laki-laki Eren dan saudara perempuan angkatnya Mikasa menyaksikan sesuatu yang mengerikan saat tembok kota dihancurkan oleh Titan Kolosal yang muncul dari udara tipis. Saat Titan yang lebih kecil membanjiri kota, kedua anak itu menyaksikan dengan ngeri saat ibu mereka dimakan hidup-hidup. Eren bersumpah bahwa dia akan membunuh setiap Titan dan membalas dendam untuk seluruh umat manusia', '/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg', '/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg', array['Action', 'Adventure', 'Animation'], false, true, true),
('aspirants-2021', 'Aspirants', 'series', 124411, 'tt14392248', 11, 9.1, 319106, 2021, 'Unknown', 'TV', '1 Musim', 'IMDb 9.1', 'Aspirants is a story of 3 friends - Abhilash, SK, and Guri. The story takes place in the past and the present where the past captures the struggle and the drama behind the making of UPSC CSE aspirants in Old Rajinder Nagar of Delhi, while the present talks about the aftermath. It is the story of three UPSC aspirants journey.', '/lG8wK40jH4EX6dbVFI1fzw2E96N.jpg', '/1g3856hsrYrSp6gWQMUpwqDw8Nb.jpg', array['Drama'], false, true, true),
('fullmetal-alchemist-brotherhood-2009', 'Fullmetal Alchemist: Brotherhood', 'series', 31911, 'tt1355642', 12, 9.1, 250546, 2009, 'Unknown', 'TV', '1 Musim', 'IMDb 9.1', 'Disregard for alchemy’s laws ripped half of Edward Elric’s limbs from his body and left his brother Alphonse’s soul clinging to a suit of armor. To restore what was lost, the brothers seek the Philosopher’s Stone. Enemies and allies – the corrupt military, the Homunculi, and foreign alchemists – will alter the Elric brothers course, but their purpose will remain unchanged and their bond unbreakable.', '/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg', '/2UG177tWHy7xRmMKWJHB7nAUmKd.jpg', array['Action', 'Adventure', 'Animation'], false, true, true),
('gullak-2019', 'Gullak', 'series', 90966, 'tt10530900', 13, 9.1, 30805, 2019, 'Unknown', 'TV', '1 Musim', 'IMDb 9.1', 'Set in quaint by-lanes in the heart of India, Gullak is a collection of disarming and relatable tales of the Mishra family.', '/yvUFbucJg19kaR1HMNc7FKdEwYl.jpg', '/t0J74zw5N5Ux7CvvBtIHvjnSB4n.jpg', array['Comedy', 'Drama', 'Family'], false, true, true),
('sherlock-2010', 'Sherlock', 'series', 19885, 'tt1475582', 14, 9.0, 1090680, 2010, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.', '/7WTsnHkbA0FaG6R9twfFde0I9hl.jpg', '/8rvLEmdI4gLrMO1rLqbNdnNcPFE.jpg', array['Crime', 'Drama', 'Mystery'], false, true, true),
('better-call-saul-2015', 'Better Call Saul', 'series', 60059, 'tt3032476', 15, 9.0, 840697, 2015, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'Prekuel "Breaking Bad" yang mendapatkan nominasi Emmy ini berkisah tentang transformasi Jimmy McGill menjadi Saul Goodman, pengacara yang moralnya dipertanyakan.', '/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg', '/og2jKploGHYnCz68vV1nRSEE0xV.jpg', array['Crime', 'Drama'], false, true, true),
('the-office-2005', 'The Office', 'series', 2316, 'tt0386676', 16, 9.0, 835622, 2005, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'The everyday lives of office employees in the Scranton, Pennsylvania branch of the fictional Dunder Mifflin Paper Company.', '/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg', '/mLyW3UTgi2lsMdtueYODcfAB9Ku.jpg', array['Comedy'], false, true, true),
('rick-and-morty-2013', 'Rick and Morty', 'series', 60625, 'tt2861424', 17, 9.0, 697695, 2013, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'Rick adalah orang tua yang tidak seimbang secara mental tetapi berbakat secara ilmiah yang baru-baru ini terhubung kembali dengan keluarganya. Dia menghabiskan sebagian besar waktunya dengan melibatkan cucunya yang muda, Morty, dalam petualangan berbahaya dan aneh di luar angkasa dan alam semesta alternatif. Ditambah dengan kehidupan keluarga Morty yang sudah tidak stabil, peristiwa-peristiwa ini menyebabkan Morty sangat tertekan di rumah dan sekolah.', '/owhkU6KRqdXoUQpjV8uyZGPtX58.jpg', '/9In9QgVJx7PlFOAgVHCKKSbo605.jpg', array['Adventure', 'Animation', 'Comedy'], false, true, true),
('arcane-2021', 'Arcane', 'series', 94605, 'tt11126994', 18, 9.0, 446561, 2021, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'Di tengah perselisihan tajam antar sepasang kota kembar, Piltover dan Zaun, dua saudari bertempur sebagai musuh dalam perang antara teknologi sihir dan konflik keyakinan.', '/abf8tHznhSvl9BAElD2cQeRr7do.jpg', '/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg', array['Action', 'Adventure', 'Animation'], false, false, true),
('one-piece-1999', 'One Piece', 'series', 37854, 'tt0388629', 19, 9.0, 356237, 1999, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'Gol D Roger dikenal sebagai Raja Bajak Laut, Orang terkuat dan paling terkenal yang pernah mengarungi Grand Line. Penangkapan dan Eksekusi Roger oleh Pemerintahan Dunia telah membawa perubahan di seluruh dunia. Kata kata terakhir sebelum kematiannya mengungkapkan lokasi dari harta karun terbesar di dunia, One Piece. Inilah awal dari era bajak laut, semua orang bermimpi menemukan One Piece (yang mana menjanjikan harta dan tahta yang tak terhingga jumlahnya), dan tentunya merebut gelar dari orang yang pertama menemukannya, gelar Raja Bajak Laut. Monkey D Luffy.', '/dB4EDhre2dsC2kxYDavyKWqLQwi.jpg', '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg', array['Action', 'Adventure', 'Animation'], false, false, true),
('hunter-x-hunter-2011', 'Hunter x Hunter', 'series', 46298, 'tt2098220', 20, 9.0, 196708, 2011, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'Suatu hari Gon Freecss yang berusia dua belas tahun menemukan bahwa ayah yang selalu diberi tahu bahwa ayahnya sudah mati, masih hidup dan sehat. Ayahnya, Ging, adalah seorang Pemburu — anggota elit masyarakat dengan izin untuk pergi ke mana pun atau melakukan hampir semua hal. Gon, yang bertekad untuk mengikuti jejak ayahnya, memutuskan untuk mengambil Ujian Hunter dan akhirnya menemukan ayahnya untuk membuktikan dirinya sebagai seorang Pemburu dengan haknya sendiri. Namun di tengah jalan, dia belajar bahwa ada lebih banyak untuk menjadi seorang Pemburu daripada yang diperkirakan sebelumnya, dan tantangan yang harus dia hadapi dianggap sebagai yang terberat di dunia.', '/i2EEr2uBvRlAwJ8d8zTG2Y19mIa.jpg', '/bFKKyCI89Xq98Gul8cGox8K3sZa.jpg', array['Action', 'Adventure', 'Animation'], false, false, true),
('dexter-resurrection-2025', 'Dexter: Resurrection', 'series', 259909, 'tt33043892', 21, 9.0, 146108, 2025, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'Dexter Morgan awakens from a coma to find Harrison gone without a trace. Realizing the weight of what he put his son through, Dexter sets out for New York City, determined to find him and make things right. But closure won''t come easy. When Miami Metro''s Angel Batista arrives with questions, Dexter realizes his past is catching up to him fast. As father and son navigate their own darkness in the city that never sleeps, they soon find themselves deeper than they ever imagined - and that the only way out is together.', '/kEHZfSZhZKDot4wqurgIzMUNq1W.jpg', '/8J0SjKToFBbg8dKpocVOCsrC77C.jpg', array['Crime', 'Drama', 'Mystery'], false, false, true),
('batman-the-animated-series-1992', 'Batman: The Animated Series', 'series', 2098, 'tt0103359', 22, 9.0, 137640, 1992, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'Vowing to avenge the murder of his parents, Bruce Wayne devotes his life to wiping out crime in Gotham City as the masked vigilante "Batman".', '/lBomQFW1vlm1yUYMNSbFZ45R4Ox.jpg', '/4QnFxk03yAn7U2ZTL5oMCCqxlPc.jpg', array['Action', 'Adventure', 'Animation'], false, false, true),
('panchayat-2020', 'Panchayat', 'series', 101352, 'tt12004706', 23, 9.0, 117824, 2020, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'Panchayat is a comedy-drama, which captures the journey of an engineering graduate Abhishek, who for lack of a better job option joins as secretary of a panchayat office in a remote village of Uttar Pradesh. Stuck between crazy villagers and a difficult village lifestyle Abhishek starts his job with the sole motivation of getting out of there as soon as possible, for which he even prepares for CAT.', '/xrfvAhrMdT6Uwg5fyTyQAZBYyiu.jpg', '/iZ8EtGAqKWZdRJPzWfFseNfVxjh.jpg', array['Comedy', 'Drama'], false, false, true),
('the-twilight-zone-1959', 'The Twilight Zone', 'series', 6357, 'tt0052520', 24, 9.0, 108904, 1959, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'An anthology series containing drama, psychological thriller, fantasy, science fiction, suspense, and/or horror, often concluding with a macabre or unexpected twist.', '/7uY4pCOxbEdv4M8jTE4uMPVoSIW.jpg', '/zAgcM7zwWAVOIT9dMMzQx7e4vdX.jpg', array['Drama', 'Fantasy', 'Horror'], false, false, true),
('leyla-and-mecnun-2011', 'Leyla and Mecnun', 'series', 40417, 'tt1831164', 25, 9.0, 103725, 2011, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'Leyla ile Mecnun is a Turkish television comedy series. The show is set in Istanbul, Turkey and premiered in 2011 on TRT. The series is a surreal and absurd comedy that revolves around the fictional love story between Leyla and Mecnun.', '/3jPLJJXbFabb29mOxZOK0xctcy6.jpg', '/aEQEIXDmjd9otezUu64VFmpO51K.jpg', array['Adventure', 'Comedy', 'Drama'], false, false, true),
('kota-factory-2019', 'Kota Factory', 'series', 89113, 'tt9432978', 26, 9.0, 92488, 2019, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'In a city of coaching centers known to train India’s finest collegiate minds, an earnest but unexceptional student and his friends navigate campus life.', '/fMBookmwL6HjIgIVTjQ6EMr3pCH.jpg', '/mQEmKXSFlzBlSoYgut0VfjxAzoA.jpg', array['Comedy', 'Drama'], false, false, true),
('clarkson-s-farm-2021', 'Clarkson''s Farm', 'series', 117648, 'tt10541088', 27, 9.0, 86526, 2021, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'Follow Jeremy Clarkson as he embarks on his latest adventure, farming. The man who on several occasions claims to be allergic to manual labour takes on the most manually labour intensive job there is. What could possibly go wrong?', '/toVhyqMT3ICfahE7Ad8obJvZHpX.jpg', '/i50h4Gz6e9BMGak5l6gg5qfIjcv.jpg', array['Comedy', 'Documentary', 'Reality-TV'], false, false, true),
('tvf-pitchers-2015', 'TVF Pitchers', 'series', 63180, 'tt4742876', 28, 9.0, 79787, 2015, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'A story of trials and tribulations of four young entrepreneurs who quit their day jobs in order to pursue their start up venture.', '/w0A288hXCytNIi9Kh7VkKE8MQ1W.jpg', '/AkhbsjGma7KnwN8Z63yqGMrunv6.jpg', array['Comedy', 'Drama'], false, false, true),
('sandeep-bhaiya-2023', 'Sandeep Bhaiya', 'series', 229429, 'tt28227737', 29, 9.0, 77265, 2023, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', '‘Sandeep Bhaiya’ is a spinoff of the blockbuster webshow TVF Aspirants. It will have a total of eight episodes and is inspired by his iconic character in TVF Aspirants.', '/m9ILwngvdDfznuXFwkle0sEQrjW.jpg', '/pYzW7v7X3qbaR5EJgUoKXfFPiIt.jpg', array['Drama'], false, false, true),
('bleach-thousand-year-blood-war-2022', 'Bleach: Thousand-Year Blood War', 'series', 308329, 'tt14986406', 30, 9.0, 76840, 2022, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'After the brief lull that followed the previous battles, Ichigo and his companions find themselves facing new enemies, who this time manage to strike right at the heart of Soul Society and declare war on the Shinigami. Ghosts from the past, revelations, and relentless, life-or-death battles will fill the adaptation of the final story arc of Tite Kubo’s manga.', '/6gCo1tBFiPFDJL0JHJuzWPurcIr.jpg', '/arGsmUU6DCwPTRrpbZnDmP3myRH.jpg', array['Action', 'Adventure', 'Animation'], false, false, true),
('only-fools-and-horses-1981', 'Only Fools and Horses', 'series', 72, 'tt0081912', 31, 9.0, 66226, 1981, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'Only Fools and Horses.... Is a British sitcom created and written by John Sullivan. Seven series were originally transmitted on BBC One from 1981 to 1991, with sixteen sporadic Christmas specials aired until 2003. In working-class Peckham in south-east London, ambitious market trader Derek ''Del Boy'' Trotter and his younger half-brother Rodney, explore their highs and lows in life, in particular their attempts to get rich. Initially not an immediate hit and receiving little promotion early on, it later achieved consistently high ratings, and the 1996 episode "Time on Our Hands" (originally billed as the series finale) holds the record for the biggest UK audience for a sitcom episode, attracting 24.3 million viewers. The series bears a significant influence on British culture, contributing several words and phrases to the English language.', '/8QznQBwr4aqPIQTiymL7obM3qOK.jpg', '/K8oVAMcE19IvzJsPlRVfDnB4Zq.jpg', array['Comedy'], false, false, true),
('when-life-gives-you-tangerines-2025', 'When Life Gives You Tangerines', 'series', 219246, 'tt26471411', 32, 9.0, 39978, 2025, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'Di Jeju, kisah gadis energik dan pemuda gigih di pulau itu bersemi jadi riwayat panjang penuh kegagalan dan kesuksesan—bukti bahwa cinta bisa bertahan melintasi waktu.', '/1VC3sEFxYXYDqQUCAnvWfUsYg1s.jpg', '/mwczMJeoQrsPERcyP1e900jo3Jv.jpg', array['Drama', 'History', 'Romance'], false, false, true),
('as-if-2021', 'As If', 'series', 115678, 'tt13675832', 33, 9.0, 36907, 2021, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'Yılmaz and İlkkan are two friends who are constantly fighting each other. Their biggest feature is always being able to do things that will turn their ordinary lives upside down. They magnify small events incredibly and give you a nervous breakdown. They are the embodiment of the misfortunes, strange events and despair we experience every day.', '/y1uhSlwcjuzOTxviRDqiMkExnVv.jpg', '/p7VgbdDN2LK41JTavzJ9x3i4ktE.jpg', array['Comedy'], false, false, true),
('taskmaster-2015', 'Taskmaster', 'series', 63404, 'tt4934214', 34, 9.0, 31672, 2015, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'Greg Davies is the Taskmaster, and with the help of his ever-loyal assistant Alex Horne, they will set out to test the wiles, wit, wisdom and skills of five hyper-competitive comedians. Who will be crowned the Taskmaster champion?', '/oHLZyN7G7EpXCHxYdpMcuUNCUgS.jpg', '/wQc6l7RaUi7cPMuCTNnYMKCjvUt.jpg', array['Comedy', 'Game-Show'], false, false, true),
('ramayan-1987', 'Ramayan', 'series', 1990, 'tt0268093', 35, 9.0, 27794, 1987, 'Unknown', 'TV', '1 Musim', 'IMDb 9.0', 'Ramayan is a highly successful and phenomenally popular Indian epic television series created, written, and directed by Ramanand Sagar. The 78 episode series originally aired weekly on Doordarshan from 25 January 1987, to 31 July 1988, on Sundays at 9:30 a.m. IST. It is a television adaptation of the ancient Indian Hindu religious epic of the same name and is primarily based on Valmiki''s Ramayan and Tulsidas'' Ramcharitmanas. It is also partly derived from portions of Kamban''s Ramavataram and other works.', '/gIOtRVKHHyPtyGPsLLhzhSYG1QF.jpg', '/sjaJaXRjp6FrJccBAWup9a8TQ7f.jpg', array['Adventure', 'Drama', 'Family'], false, false, true),
('death-note-2006', 'Death Note', 'series', 13916, 'tt0877057', 36, 8.9, 484379, 2006, 'Unknown', 'TV', '1 Musim', 'IMDb 8.9', 'Pelajar SMA Jepang menemukan buku catatan mistis, yang memberinya kekuatan untuk membunuh siapa pun dengan menuliskan namanya di buku tersebut.', '/tCZFfYTIwrR7n94J6G14Y4hAFU6.jpg', '/koBa94NxTaGe2FoDzlXMuJptsv0.jpg', array['Animation', 'Crime', 'Drama'], false, false, true),
('seinfeld-1989', 'Seinfeld', 'series', 1400, 'tt0098904', 37, 8.9, 385114, 1989, 'Unknown', 'TV', '1 Musim', 'IMDb 8.9', 'A stand-up comedian and his three offbeat friends weather the pitfalls and payoffs of life in New York City in the ''90s. It''s a show about nothing.', '/aCw8ONfyz3AhngVQa1E2Ss4KSUQ.jpg', '/tMRdEsMg9MyXAkcufK9YJEeIaNW.jpg', array['Comedy'], false, false, true),
('firefly-2002', 'Firefly', 'series', 1437, 'tt0303461', 38, 8.9, 302332, 2002, 'Unknown', 'TV', '1 Musim', 'IMDb 8.9', 'In the year 2517, the universe is a vast frontier where lawlessness reigns and adventure awaits! Join Captain Malcolm Reynolds and his ragtag crew aboard the spaceship Serenity as they navigate the fringes of society, battling the oppressive Alliance and facing off against ruthless bounty hunters.', '/vZcKsy4sGAvWMVqLluwYuoi11Kj.jpg', '/te4VJNMipsFQofCkiytuyswGDlV.jpg', array['Adventure', 'Sci-Fi'], false, false, true),
('gravity-falls-2012', 'Gravity Falls', 'series', 40075, 'tt1865718', 39, 8.9, 179886, 2012, 'Unknown', 'TV', '1 Musim', 'IMDb 8.9', 'Twin brother and sister Dipper and Mabel Pines are in for an unexpected adventure when they spend the summer helping their great uncle Stan run a tourist trap in the mysterious town of Gravity Falls, Oregon.', '/qwi3p6PzKfQZ4YXBzv3CP5pO2dE.jpg', '/lhg7eA6CTOCL10QNVdKiyxkgPsL.jpg', array['Adventure', 'Animation', 'Comedy'], false, false, true),
('cowboy-bebop-1998', 'Cowboy Bebop', 'series', 30991, 'tt0213338', 40, 8.9, 170013, 1998, 'Unknown', 'TV', '1 Musim', 'IMDb 8.9', 'In 2071, roughly fifty years after an accident with a hyperspace gateway made the Earth almost uninhabitable, humanity has colonized most of the rocky planets and moons of the Solar System. Amid a rising crime rate, the Inter Solar System Police (ISSP) set up a legalized contract system, in which registered bounty hunters, also referred to as "Cowboys", chase criminals and bring them in alive in return for a reward.', '/xDiXDfZwC6XYC6fxHI1jl3A3Ill.jpg', '/A4PHx94G7mvM3b8vsDJ5HEaQ6uv.jpg', array['Action', 'Adventure', 'Animation'], false, false, true),
('the-pitt-2025', 'The Pitt', 'series', 250307, 'tt31938062', 41, 8.9, 153661, 2025, 'Unknown', 'TV', '1 Musim', 'IMDb 8.9', 'The staff of Pittsburgh''s Trauma Medical Center work around the clock to save lives in an overcrowded and underfunded emergency department.', '/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg', '/7Sgo1XdCrIpJpiNsTPMi9vwKSuC.jpg', array['Drama'], false, false, true),
('the-west-wing-1999', 'The West Wing', 'series', 688, 'tt0200276', 42, 8.9, 99641, 1999, 'Unknown', 'TV', '1 Musim', 'IMDb 8.9', 'The West Wing provides a glimpse into presidential politics in the nation''s capital as it tells the stories of the members of a fictional presidential administration. These interesting characters have humor and dedication that touches the heart while the politics that they discuss touch on everyday life.', '/yqDWr5NAE7m1IWrygYwLyEB6pN0.jpg', '/o6ixncGLOtRPz78vEIy9p1cOn9J.jpg', array['Drama'], false, false, true),
('sousou-no-frieren-2023', 'Sousou no Frieren', 'series', 209867, 'tt22248376', 43, 8.9, 77556, 2023, 'Unknown', 'TV', '1 Musim', 'IMDb 8.9', 'Setelah petualangan 10 tahun dengan pahlawan Himmel dan teman-teman, Frieren mengalahkan raja iblis dan berhasil membawa perdamaian dunia. Frieren yang merupakan seorang elf berusia lebih dari seribu tahun, berjanji untuk pergi menemui Himmel dan kawan-kawan lagi. Lima puluh tahun kemudian, Frieren bertemu dengan Himmel, tetapi Himmel sudah tua dan hanya memiliki sedikit waktu untuk hidup. Setelah menyaksikan kematian Himmel, ia menyadari dirinya tak pernah benar-benar "mengenal seseorang". Frieren yang menyesal kemudian memulai perjalanan untuk lebih "mengenal orang". Dalam perjalanan itu, ia berjumpa dengan berbagai orang dan peristiwa...', '/dqZENchTd7lp5zht7BdlqM7RBhD.jpg', '/rBOnrVlck7BIlGeWVlzYiZeg4l2.jpg', array['Adventure', 'Animation', 'Comedy'], false, false, true),
('persona-2018', 'Persona', 'series', 77994, 'tt7920978', 44, 8.9, 56739, 2018, 'Unknown', 'TV', '1 Musim', 'IMDb 8.9', 'After being diagnosed with Alzheimer''s, a retired judicial officer decides to commit a murder that he had been planning for years.', '/OjvNOeB55tVymgybfWZOD7yXAF.jpg', '/3MfziPWYvHaYwTdi5jxkEscjHVw.jpg', array['Crime', 'Drama', 'Mystery'], false, false, true),
('nathan-for-you-2013', 'Nathan for You', 'series', 58957, 'tt2297757', 45, 8.9, 50061, 2013, 'Unknown', 'TV', '1 Musim', 'IMDb 8.9', 'Self-proclaimed business expert, writer, director and comedian Nathan Fielder helps real small businesses turn a profit with marketing tactics that no ordinary consultant would dare to attempt. From driving foot traffic to an off-the-strip souvenir shop by using Hollywood flair and a Johnny Depp impersonator, to creating a rebate that can only be redeemed by climbing a mountain, to founding a coffee shop called "Dumb Starbucks,” Nathan has always gone to the limit to make his ideas come to life. With his unorthodox approach to problem solving, Nathan’s genuine efforts to do good often draw the real people he encounters into an experience far beyond what they signed up for.', '/6tGXlz61c44onUg6EdRkbhjcaPA.jpg', '/5ix5qtVlLR2O0sgAJp5urHLbGZe.jpg', array['Comedy', 'Documentary'], false, false, true),
('undercover-2011', 'Undercover', 'series', 43424, 'tt1909015', 46, 8.9, 28390, 2011, 'Unknown', 'TV', '1 Musim', 'IMDb 8.9', 'Just an ordinary boy from the Sofia suburbs becomes the first bulgarian undercover cop. Forced by his father when he was young to lie and cheat, Martin becomes the perfect liar. That skill, and also the hatred of the ''underworld'' makes him the perfect match for a dangerous mission - to infiltrate the crime organisation of a rich and powerful businessman. While infiltrating and living in fear of being uncovered, Martin falls in love with the most inappropriate woman - Djaro''s girlfriend, Suni. Just when he gains the trust of the mobsters, it appears that the real enemy is in the police. Martin is alone against all, facing difficult decisions.', '/x1XPfSUFnrBYZgEmFmSwWqVJDjt.jpg', '/ic2zzHB9C2LMsWmmYcMUHA1W8Yq.jpg', array['Action', 'Crime', 'Drama'], false, false, true),
('yeh-meri-family-2018', 'Yeh Meri Family', 'series', 81166, 'tt8595766', 47, 8.9, 27745, 2018, 'Unknown', 'TV', '1 Musim', 'IMDb 8.9', 'Set in the summer of 1998 it is a story about conflicting emotions towards family members from the eyes of a twelve year old.', '/7F33yqUYIzmFQwDibEjPoJxxTXg.jpg', '/iKIfIOPdD0pZsR2KbvTpv4kgsnT.jpg', array['Comedy', 'Drama', 'Family'], false, false, true),
('mahabharat-1988', 'Mahabharat', 'series', 12605, 'tt0158417', 48, 8.9, 27475, 1988, 'Unknown', 'TV', '1 Musim', 'IMDb 8.9', 'A dynastic struggle occurs for the throne of Hastinapur, the kingdom ruled by the Kuru clan, between the Kauravas and Pandavas, collateral branches of the clan, which causes the Kurukshetra War.', '/FZJMIxK1AI1VMbeazdc030Qwat.jpg', '/a7oZ4AMrR7y3q0xm6VHb4FxXGED.jpg', array['Action', 'Adventure', 'Drama'], false, false, true),
('friends-1994', 'Friends', 'series', 1668, 'tt0108778', 49, 8.8, 1194724, 1994, 'Unknown', 'TV', '1 Musim', 'IMDb 8.8', 'Six young people from New York City, on their own and struggling to survive in the real world, find the companionship, comfort and support they get from each other to be the perfect antidote to the pressures of life.', '/2koX1xLkpTQM4IZebYvKysFW1Nh.jpg', '/m3Jev59mJLyUp5bXhY5SVfIBZI0.jpg', array['Comedy', 'Romance'], false, false, true),
('true-detective-2014', 'True Detective', 'series', 46648, 'tt2356777', 50, 8.8, 757871, 2014, 'Unknown', 'TV', '1 Musim', 'IMDb 8.8', 'An American anthology police detective series utilizing multiple timelines in which investigations seem to unearth personal and professional secrets of those involved, both within or outside the law.', '/zYqVTiHK5ZajYcNzAW7qWte5NWS.jpg', '/v8YFr8BbU9qsO8PYIulzTeM6Qk.jpg', array['Crime', 'Drama', 'Mystery'], false, false, true)
on conflict (slug) do update set
  title = excluded.title,
  type = excluded.type,
  tmdb_id = excluded.tmdb_id,
  imdb_id = excluded.imdb_id,
  imdb_rank = excluded.imdb_rank,
  imdb_rating = excluded.imdb_rating,
  imdb_votes = excluded.imdb_votes,
  year = excluded.year,
  country = excluded.country,
  network = excluded.network,
  duration = excluded.duration,
  rating = excluded.rating,
  synopsis = excluded.synopsis,
  poster_path = excluded.poster_path,
  backdrop_path = excluded.backdrop_path,
  genre_names = excluded.genre_names,
  is_published = excluded.is_published,
  is_featured = excluded.is_featured,
  is_trending = excluded.is_trending,
  is_recently_added = excluded.is_recently_added,
  updated_at = now();

insert into public.video_sources (title_id, label, type, url, quality, is_active)
select
  titles.id,
  'NxSha TMDb/IMDb embed',
  'official_embed',
  case when titles.type = 'series' then 'https://web.nxsha.app/embed/tv/' || titles.tmdb_id || '/1/1?sub=id&lang=id' else 'https://web.nxsha.app/embed/movie/' || titles.tmdb_id || '?sub=id&lang=id' end,
  '1080p',
  true
from public.titles
where titles.imdb_id is not null
  and not exists (
    select 1 from public.video_sources where video_sources.title_id = titles.id and video_sources.label = 'NxSha TMDb/IMDb embed'
  );

with series_data(slug, season_count, poster_path) as (
  values
('breaking-bad-2008', 1, '/3xnWaLQjelJDDF7LT1WBo6f4BRe.jpg'),
('avatar-the-last-airbender-2005', 1, '/7nYD5vKvr0JVxkl6QNCkLSQZfHJ.jpg'),
('the-wire-2002', 1, '/4lbclFySvugI51fwsyxBTOm4DqK.jpg'),
('bluey-2018', 1, '/b9mY0X5T20ZM073hoa5n0dgmbfN.jpg'),
('game-of-thrones-2011', 1, '/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg'),
('the-sopranos-1999', 1, '/rTc7ZXdroqjkKivFPvCPX0Ru7uw.jpg'),
('sapne-vs-everyone-2023', 1, '/ajBMZ9JNpfrecj4xpZz49tCONBm.jpg'),
('our-planet-2019', 1, '/wRSnArnQBmeUYb5GWDU595bGsBr.jpg'),
('the-world-at-war-1973', 1, '/bWdwEYQQEsz9HuXy5m95z95BYQM.jpg'),
('shingeki-no-kyojin-2013', 1, '/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg'),
('aspirants-2021', 1, '/lG8wK40jH4EX6dbVFI1fzw2E96N.jpg'),
('fullmetal-alchemist-brotherhood-2009', 1, '/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg'),
('gullak-2019', 1, '/yvUFbucJg19kaR1HMNc7FKdEwYl.jpg'),
('sherlock-2010', 1, '/7WTsnHkbA0FaG6R9twfFde0I9hl.jpg'),
('better-call-saul-2015', 1, '/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg'),
('the-office-2005', 1, '/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg'),
('rick-and-morty-2013', 1, '/owhkU6KRqdXoUQpjV8uyZGPtX58.jpg'),
('arcane-2021', 1, '/abf8tHznhSvl9BAElD2cQeRr7do.jpg'),
('one-piece-1999', 1, '/dB4EDhre2dsC2kxYDavyKWqLQwi.jpg'),
('hunter-x-hunter-2011', 1, '/i2EEr2uBvRlAwJ8d8zTG2Y19mIa.jpg'),
('dexter-resurrection-2025', 1, '/kEHZfSZhZKDot4wqurgIzMUNq1W.jpg'),
('batman-the-animated-series-1992', 1, '/lBomQFW1vlm1yUYMNSbFZ45R4Ox.jpg'),
('panchayat-2020', 1, '/xrfvAhrMdT6Uwg5fyTyQAZBYyiu.jpg'),
('the-twilight-zone-1959', 1, '/7uY4pCOxbEdv4M8jTE4uMPVoSIW.jpg'),
('leyla-and-mecnun-2011', 1, '/3jPLJJXbFabb29mOxZOK0xctcy6.jpg'),
('kota-factory-2019', 1, '/fMBookmwL6HjIgIVTjQ6EMr3pCH.jpg'),
('clarkson-s-farm-2021', 1, '/toVhyqMT3ICfahE7Ad8obJvZHpX.jpg'),
('tvf-pitchers-2015', 1, '/w0A288hXCytNIi9Kh7VkKE8MQ1W.jpg'),
('sandeep-bhaiya-2023', 1, '/m9ILwngvdDfznuXFwkle0sEQrjW.jpg'),
('bleach-thousand-year-blood-war-2022', 1, '/6gCo1tBFiPFDJL0JHJuzWPurcIr.jpg'),
('only-fools-and-horses-1981', 1, '/8QznQBwr4aqPIQTiymL7obM3qOK.jpg'),
('when-life-gives-you-tangerines-2025', 1, '/1VC3sEFxYXYDqQUCAnvWfUsYg1s.jpg'),
('as-if-2021', 1, '/y1uhSlwcjuzOTxviRDqiMkExnVv.jpg'),
('taskmaster-2015', 1, '/oHLZyN7G7EpXCHxYdpMcuUNCUgS.jpg'),
('ramayan-1987', 1, '/gIOtRVKHHyPtyGPsLLhzhSYG1QF.jpg'),
('death-note-2006', 1, '/tCZFfYTIwrR7n94J6G14Y4hAFU6.jpg'),
('seinfeld-1989', 1, '/aCw8ONfyz3AhngVQa1E2Ss4KSUQ.jpg'),
('firefly-2002', 1, '/vZcKsy4sGAvWMVqLluwYuoi11Kj.jpg'),
('gravity-falls-2012', 1, '/qwi3p6PzKfQZ4YXBzv3CP5pO2dE.jpg'),
('cowboy-bebop-1998', 1, '/xDiXDfZwC6XYC6fxHI1jl3A3Ill.jpg'),
('the-pitt-2025', 1, '/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg'),
('the-west-wing-1999', 1, '/yqDWr5NAE7m1IWrygYwLyEB6pN0.jpg'),
('sousou-no-frieren-2023', 1, '/dqZENchTd7lp5zht7BdlqM7RBhD.jpg'),
('persona-2018', 1, '/OjvNOeB55tVymgybfWZOD7yXAF.jpg'),
('nathan-for-you-2013', 1, '/6tGXlz61c44onUg6EdRkbhjcaPA.jpg'),
('undercover-2011', 1, '/x1XPfSUFnrBYZgEmFmSwWqVJDjt.jpg'),
('yeh-meri-family-2018', 1, '/7F33yqUYIzmFQwDibEjPoJxxTXg.jpg'),
('mahabharat-1988', 1, '/FZJMIxK1AI1VMbeazdc030Qwat.jpg'),
('friends-1994', 1, '/2koX1xLkpTQM4IZebYvKysFW1Nh.jpg'),
('true-detective-2014', 1, '/zYqVTiHK5ZajYcNzAW7qWte5NWS.jpg')
),
series_titles as (
  select titles.id, titles.slug, titles.title, titles.synopsis, series_data.season_count, series_data.poster_path
  from public.titles
  join series_data on series_data.slug = titles.slug
),
season_numbers as (
  select series_titles.*, generate_series(1, series_titles.season_count) as season_number
  from series_titles
),
upserted_seasons as (
  insert into public.seasons (title_id, season_number, name, synopsis, poster_path, is_published)
  select id, season_number, 'Season ' || season_number, title || ' season ' || season_number || '.', poster_path, true
  from season_numbers
  on conflict (title_id, season_number) do update set
    name = excluded.name,
    synopsis = excluded.synopsis,
    poster_path = excluded.poster_path,
    is_published = excluded.is_published,
    updated_at = now()
  returning id, title_id, season_number
)
insert into public.episodes (title_id, season_id, season_number, episode_number, title, synopsis, duration, still_path, is_published)
select
  upserted_seasons.title_id,
  upserted_seasons.id,
  upserted_seasons.season_number,
  episode_number,
  'Episode ' || episode_number,
  'Episode ' || episode_number || ' season ' || upserted_seasons.season_number || '.',
  'TBA',
  titles.backdrop_path,
  true
from upserted_seasons
join public.titles on titles.id = upserted_seasons.title_id
cross join lateral generate_series(1, 8) as episode_number
on conflict (title_id, season_number, episode_number) do update set
  season_id = excluded.season_id,
  title = excluded.title,
  synopsis = excluded.synopsis,
  duration = excluded.duration,
  still_path = excluded.still_path,
  is_published = excluded.is_published,
  updated_at = now();
